apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent-storage.yaml
  - qdrant-storage.yaml
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - qdrant-deployment.yaml

commonLabels:
  app: prompt-template-system

namespace: default

images:
  - name: ${REGISTRY_URL}/prompt-template-backend
    newName: ${REGISTRY_URL}/prompt-template-backend
    newTag: latest
  - name: ${REGISTRY_URL}/prompt-template-frontend
    newName: ${REGISTRY_URL}/prompt-template-frontend
    newTag: latest 