apiVersion: v1
kind: PersistentVolume
metadata:
  name: prompt-template-qdrant-pv
  labels:
    type: local
    app: prompt-template-system
    component: qdrant
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prompt-template-qdrant"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prompt-template-qdrant-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: prompt-template-system
      component: qdrant 